name: Mirror repos
on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with GitHub
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials

          git config --global url.https://github.com/.insteadOf ssh://git@github.com:
          git config --global url.https://github.com/.insteadOf git@github.com:
      - name: Run the mirror script
        run: python mirror.py
